const postIds = [
  "S94e3ka5HzB",
  "MBZlnwvLlYW",
  "N2sbaI4btqf",
  "6cmih9SKE9N",
  "E-vkN7l77nY",
  "ZR8DbTnpEio",
  "p8Zgup10vDy",
  "xEl5XnwrgiE",
  "pjtWsYHmLiL",
  "7kMrOcec2dH",
  "W6oYSI_ZVkI",
  "8MKwyHfOigS",
  "vCZK8HLeeLg",
  "E2jJxwgMuCZ",
  "LZf1Z_LYbRO",
  "1OcbeyeB1W4",
  "lcIGGbOENo9",
  "jzoTldbIEdn",
  "HhuWsv0dXo1",
  "DBbnLv_RM1_",
  "IOiCWqsVRtR",
  "pdoTrY5sP6t",
  "kYQCeqohr1o",
  "mwQiyhC-dSz",
  "0Z17IAwxWsU",
  "Fl5b7_5lKHQ",
  "7ZbuDXY8wwX",
  "x_1aGImWY1f",
  "f3wkql0J-kK",
  "ZUxzYFbAuAm",
  "qbuRGxdu5p-",
  "SI9EwzcW3dh",
  "EWMkN3kudYo",
  "_w7Jl_qicKN",
  "Lvt0axlLoQK",
  "vj1kWeM4id1",
  "4Q3CY6OgVn7",
  "DGk89Ium_yL",
  "637C5TbA5nn",
  "nR5rwErj_5N",
  "BJJzd9S3CWA",
  "58Ck8doWZ1U",
  "KY3fS2Bl5Mg",
  "ipI6vCrKovh",
  "bTcCqsXLg9Z",
  "TbyeHTKqyRm",
  "IbLKgbP5k0T",
  "kVTNxM46QMN",
];
export default function sitemap() {
  const staticRoutes = [
    {
      url: "https://pths-cowbell.vercel.app",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1,
    },
    {
      url: "https://pths-cowbell.vercel.app/home",
      lastModified: new Date(),
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: "https://pths-cowbell.vercel.app/about",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.7,
    },
    {
      url: "https://pths-cowbell.vercel.app/user",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.2,
    },
  ];

  const postRoutes = postIds.map((id) => ({
    url: `https://pths-cowbell.vercel.app/post/${id}`,
    lastModified: new Date(),
    changeFrequency: "weekly",
    priority: 0.8,
  }));

  return [...staticRoutes, ...postRoutes];
}
